version: '2.1'
services:
  nginx: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.0"
    networks: 
      - frontend
    ports: 
      - "443:443"
      - "3443:3443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - core
      - preview

  core: 
    image: "pryvsa-docker-release.bintray.io/pryv/core:1.2.0"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/core/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/core/log/:/app/log/
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb
    
  preview: 
    image: "pryvsa-docker-release.bintray.io/pryv/preview:1.2.0"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/preview/log/:/app/log/
      - ${PRYV_CONF_ROOT}/preview/conf/:/app/conf/
      # Not an error: Preview accesses core's data directory readonly. 
      - ${PRYV_CONF_ROOT}/core/data/:/app/data/
    links: 
      - mongodb

  mongodb: 
    image: "pryvsa-docker-release.bintray.io/pryv/mongodb:1.2.0"
    networks: 
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/mongodb/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/mongodb/log/:/app/log/
      - ${PRYV_CONF_ROOT}/mongodb/data/:/app/data/
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
