
version: '2.1'
services:
  nginx: 
    image: "pryvsa-docker-release.bintray.io/pryv/nginx:1.2.0"
    networks: 
      - frontend
    ports: 
      - "443:443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - register
  
  dns: 
    image: "pryvsa-docker-release.bintray.io/pryv/dns:v0.1.9-140-g841b420"
    ports:
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/dns/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/dns/log/:/app/log/
    links:
      - redis
          
  register: 
    image: "pryvsa-docker-release.bintray.io/pryv/register:v0.1.9-140-g841b420"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/register/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/register/log/:/app/log/
    links:
      - redis

  redis: 
    image: "pryvsa-docker-release.bintray.io/pryv/redis:1.2.0"
    networks: 
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/redis/data/:/app/data/
      - ${PRYV_CONF_ROOT}/redis/log/:/app/log/
