
version: '2.1'
services:
  nginx: 
    image: "eu.gcr.io/pryvio/nginx:1.2.0"
    networks: 
      - frontend
    ports: 
      - "443:443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - register
  
  dns: 
    image: "eu.gcr.io/pryvio/dns:1.2.0"
    ports:
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/dns/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/dns/log/:/app/log/
    links:
      - redis
          
  register: 
    image: "eu.gcr.io/pryvio/register:1.2.0"
    networks: 
      - frontend
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/register/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/register/log/:/app/log/
    links:
      - redis

  redis: 
    image: "eu.gcr.io/pryvio/redis:1.2.0"
    networks: 
      - backend
    volumes: 
      - ${PRYV_CONF_ROOT}/redis/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/redis/data/:/app/data/
      - ${PRYV_CONF_ROOT}/redis/log/:/app/log/

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
