#!/usr/bin/env bash

[[ -e static.yml ]] || { echo >&2 "Please cd into the configuration directory before running this script."; exit 1; }

# Configuration and data files are all below this root.
export PRYV_CONF_ROOT=$PWD/static

echo "Running Pryv/static component."
exec docker-compose -f static.yml up
