version: '2.1'
services:
  nginx: 
    image: "eu.gcr.io/pryvio/nginx:1.2.0"
    networks: 
      - frontend
    ports: 
      - "443:443"
    volumes: 
      - ${PRYV_CONF_ROOT}/nginx/conf/:/app/conf/
      - ${PRYV_CONF_ROOT}/nginx/log/:/app/log/
    links: 
      - static

  static: 
    image: "eu.gcr.io/pryvio/static:1.2.0"
    volumes: 
      - ${PRYV_CONF_ROOT}/static/conf/:/app/conf/
    networks: 
      - frontend

networks:
  frontend:
    driver: bridge
