#!/usr/bin/env bash
set -e

# Builds the `pryvio/base` Docker image and others.

# Determine build tag and release status from git working copy
./check-git
version=$(cat build_tag)
if [ -e release_build ]; then
  release=true
  echo "This is a release build: it will be published to the Docker registry"
fi

host='eu.gcr.io'

cd docker
for image in base mongodb redis nginx
do
  echo ""
  echo "---------------------------- BUILD IMAGE: $image ----------------------------"
  echo ""
  docker build -f Dockerfile.$image -t $host/pryvio/$image:$version .
  if [ "$release" = true ]; then
    # publish to registry
    docker push $host/pryvio/$image:$version
  fi
done
