#!/bin/sh

set -e

conf_dir="/app/conf"
data_dir="/app/data"
log_dir="/app/log"

# Make sure that redis can write data…
chown -R redis:redis $data_dir

# …and the log file
touch $log_dir/redis.log && chown -R redis:redis $log_dir

cd /app/data/
exec chpst -u redis /usr/local/bin/redis-server /app/conf/redis.conf
