
version: '2.1'
services:
  nginx: 
    image: "pryv/nginx"
    networks: 
      - frontend
    ports: 
      - "443:443"
    links: 
      - core
      - preview
      - static
      - register
      
  register: 
    image: "pryv/register"
    networks: 
      - frontend
      - backend
    links: 
      - redis
      
  dns: 
    image: "pryv/dns"
    ports: 
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    links: 
      - redis
      
  redis: 
    image: "pryv/redis"
    networks: 
      - backend
      
  static: 
    image: "pryv/static"
    networks: 
      - frontend
  
  core: 
    image: "pryv/core"
    networks: 
      - frontend
      - backend
    links: 
      - mongodb
    
  preview: 
    image: "pryv/preview"
    networks: 
      - frontend
      - backend
    links: 
      - mongodb
      
  mongodb: 
    image: "pryv/mongodb"
    networks: 
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
