
version: '2.1'
services:
  nginx: 
    image: "pryv/nginx:1.0.4-1-g75b11f9"
    networks: 
      - frontend
    ports: 
      - "443:443"
    links: 
      - core
      - preview
      - static
      - register
      
  register: 
    image: "pryv/register:v0.1.9-37-gb627cb5"
    networks: 
      - frontend
      - backend
    volumes: 
      - /home/kschiess/pilot/register/conf/:/app/conf/
    links: 
      - redis
      
  dns: 
    image: "pryv/dns:v0.1.9-37-gb627cb5"
    ports: 
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    links: 
      - redis
      
  redis: 
    image: "pryv/redis"
    networks: 
      - backend
      
  static: 
    image: "pryv/static:0.1.1-393-g850feb9"
    networks: 
      - frontend
  
  core: 
    image: "pryv/core"
    networks: 
      - frontend
      - backend
    volumes: 
      - /home/kschiess/pilot/core/conf/:/app/conf/
    links: 
      - mongodb
    
  preview: 
    image: "pryv/preview"
    networks: 
      - frontend
      - backend
    links: 
      - mongodb
      
  mongodb: 
    image: "pryv/mongodb"
    networks: 
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
