FROM eu.gcr.io/pryvio/base:1.8.0
MAINTAINER "Tech@Pryv" <tech@pryv.com>

# add build files
COPY common-files redis /pd_build/
# install
RUN /pd_build/install.sh
# cleanup build files
RUN rm -rf /pd_build

# expose Redis port
EXPOSE 6379
