FROM nginx:1.23.1
MAINTAINER "Tech@Pryv" <tech@pryv.com>

# add build files
COPY common-files nginx /pd_build/
# install
RUN /pd_build/install.sh
# cleanup build files
RUN rm -rf /pd_build

# expose HTTP/HTTPS ports
EXPOSE 80 443
