ARG BUILD_HOST
ARG BUILD_VERSION
FROM ${BUILD_HOST}/pryvio/base:${BUILD_VERSION}
LABEL maintainer="Pryv<tech@pryv.com>"

# add build files
COPY common-files redis /pd_build/
# install
RUN /pd_build/install.sh
# cleanup build files
RUN rm -rf /pd_build

# expose Redis port
EXPOSE 6379
