
FROM phusion/baseimage:focal-1.2.0
MAINTAINER "Tech@Pryv" <tech@pryv.com>

# Note KSC, 13 Jan 17:
# Some details of the package construction are copied verbatim from
# the phusion passenger-docker recipe at https://github.com/phusion/passenger-docker

# add build files
COPY common-files base /pd_build/
# install
RUN /pd_build/install.sh
# cleanup build files
RUN rm -rf /pd_build
