
version: '2.1'
services:
  nginx: 
    image: "pryv/nginx:1.0.4-1-g75b11f9"
    networks: 
      - frontend
    ports: 
      - "443:443"
      - "3443:3443"
    volumes: 
      - /home/kschiess/pilot/nginx/conf/:/app/conf/
    links: 
      - core
      - preview
      - static
      - register
      
  register: 
    image: "pryv/register:v0.1.9-147-g0c0cd4c"
    networks: 
      - frontend
      - backend
    volumes: 
      - /home/kschiess/pilot/register/conf/:/app/conf/
    links: 
      - redis
      
  dns: 
    image: "pryv/dns:v0.1.9-147-g0c0cd4c"
    ports: 
      - "53:5353/udp"
    networks: 
      - frontend
      - backend
    links: 
      - redis
      
  redis: 
    image: "pryv/redis"
    networks: 
      - backend
      
  static: 
    image: "pryv/static:0.1.1-474-g1ea6f18"
    volumes: 
      - /home/kschiess/pilot/static/conf/:/app/conf/
    networks: 
      - frontend
  
  core: 
    image: "pryv/core:1.1.6-40-gdcddb54"
    networks: 
      - frontend
      - backend
    volumes: 
      - /home/kschiess/pilot/core/conf/:/app/conf/
      - /home/kschiess/pilot/core/data/:/app/data/
    links: 
      - mongodb
    
  preview: 
    image: "pryv/preview:1.1.6-40-gdcddb54"
    networks: 
      - frontend
      - backend
    volumes: 
      - /home/kschiess/pilot/preview/conf/:/app/conf/
      - /home/kschiess/pilot/core/data/:/app/data/
    links: 
      - mongodb
      
  mongodb: 
    image: "pryv/mongodb"
    networks: 
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
