#!/bin/sh

set -e

config_dir="/app/conf"
data_dir="/app/data"
log_dir="/app/log"

# Make sure that mongodb can write data…
chown -R mongodb:mongodb $data_dir

# …and the log file
touch $log_dir/mongodb.log && chown -R mongodb:mongodb $log_dir

cd /app/bin/mongodb
exec chpst -u mongodb bin/mongod --config $config_dir/mongodb.yml
