
version: '2.1'
services:
  nginx: 
    image: "pryv/nginx"
    networks: 
      - frontend
    ports: 
      - "80:443"
    links: 
      - core
      - preview
  
  core: 
    image: "pryv/core"
    networks: 
      - frontend
      - backend
    links: 
      - mongodb
    
  preview: 
    image: "pryv/preview"
    networks: 
      - frontend
      - backend
    links: 
      - mongodb
      
  mongodb: 
    image: "pryv/mongodb"
    networks: 
      - backend
    
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
