#!/usr/bin/env bash

# Call this script with the local name of the image you want to push to bintray. 
# The script will tag the image and push it to bintray. 
#
# Example: 
#
#     ./push_to_bintray pryv/redis 1.2.0
#

set -e

image_name=$1
image_version=$2
host='pryvsa-docker-release.bintray.io'

local_name="$image_name:$image_version"
remote_name="$host/$image_name:$image_version"

sudo docker tag $local_name $remote_name
sudo docker push $remote_name
